server:
  grpc_endpoint: 0.0.0.0:8890
  max_recv_msg_size: 4194304 # 1024 * 1024 * 4 = 4M
  callback_url: http://172.17.0.1:6668

log:
  std: true
  level: debug
  logs:
    - enable: true
      filename: log/info.log
      level: info
      max_size: 10
      max_backups: 10
      max_age: 30
    - enable: true
      filename: log/err.log
      level: error
      max_size: 10
      max_backups: 10
      max_age: 30

db:
  name: mysql # mysql | postgres | tidb | oceanbase
  mysql:
    address: localhost:3306
    user: root
    password: Wanwu123456
    database: assistant_service
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  postgres:
    address: localhost:5432
    user: postgres
    password: Wanwu123456
    database: assistant_service
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  tidb:
    address: localhost:4000
    user: root
    password: Wanwu123456
    database: assistant_service
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  oceanbase:
    address: localhost:2881
    user: root@wanwu
    password: Wanwu123456
    database: assistant_service
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true

redis:
  host: localhost
  port: 6379
  username:
  password: gromit1234
  standalone: true
  master_name: mymaster

es:
  address: elastic-wanwu:9200
  username: elastic
  password: Wanwu123456

# 智能体相关接口
assistant:
  sse-url: "http://192.168.0.21:7258/agent"