server:
  host: bff-service
  port: 6668
  external_ip: localhost
  external_port: 6668
  web_base_url: http://localhost:8081
  api_base_url: http://localhost:6668
  callback_url: http://172.17.0.1:6668

log:
  std: true
  level: debug
  logs:
    - enable: true
      filename: log/bff-info.log
      level: info
      max_size: 10
      max_backups: 10
      max_age: 30
    - enable: true
      filename: log/bff-err.log
      level: error
      max_size: 10
      max_backups: 10
      max_age: 30

jwt:
  signing-key: "zhYZAr7Q7JstuEXQBx5p2MdUtfsC7CY5"

decrypt-passwd:
  iv: "sdf4ddfsFD86Vdf2"
  key: "f5Su3GhNMM1rndyp"

i18n:
  type: jsonl
  xlsxPath: configs/microservice/bff-service/configs/wanwu-i18n.xlsx
  xlsxSheets:
    - bff-service
    - bff-custom
    - iam-service
    - model-service
    - knowledge-service
    - mcp-service
    - rag-service
    - assistant-service
    - app-service
  jsonlPath: configs/microservice/bff-service/configs/wanwu-i18n.jsonl
  langs:
    - code: zh
      name: 中文
    - code: en
      name: English
  defaultLang: zh

assistant-template:
  configPath: configs/microservice/bff-service/configs/assistant_template_config.yaml

custom-info:
  default_mode: light
  modes:
    - mode: light
      login:
        background_path: "/v1/static/logo/login_bg.png"
        logo_path: "/v1/static/logo/login_logo.png"
        login_button_color: "#384BF7"
        welcome_text: bff_custom_login_welcome_text
        platform_desc: bff_custom_login_platform_desc
      home:
        logo_path: "/v1/static/logo/title_logo.png"
        title: bff_custom_home_title
        background_color: "linear-gradient(1deg,#fff 42%,#fff 0,#ebedfe 98%,#eef0ff 0)"
      tab:
        title: bff_custom_tab_title
        logo_path: "/v1/static/logo/tab_logo.png"
      about:
        logo_path: "/v1/static/logo/about_logo.png"
        version: v0.1.0
        copyright: bff_custom_about_copyright
    - mode: dark

doc-center:
  frontend_prefix: /aibase/docCenter/pages
  links:
    - key: model
      val: 模型导入方式-详细版.md
    - key: knowledge
      val: 2.知识库/创建知识库.md
    - key: knowledge-hit
      val: 2.知识库/命中测试.md
    - key: knowledge-keywords
      val: 2.知识库/关键词管理.md
    - key: mcp
      val: 3.MCP广场.md
    - key: safety
      val: 4.安全护栏.md
    - key: rag
      val: 5.文本问答.md
    - key: agent
      val: 7.智能体.md
    - key: workflow-MCPClientNode
      val: 6.工作流/MCP.md
    - key: workflow-IntentionNode
      val: 6.工作流/意图识别.md
    - key: workflow-ApiNode
      val: 6.工作流/API.md
    - key: workflow-PythonNode
      val: 6.工作流/代码.md
    - key: workflow-LLMNode
      val: 6.工作流/大模型.md
    - key: workflow-SwitchNode
      val: 6.工作流/分支器.md
    - key: workflow-RAGNode
      val: 6.工作流/知识库.md
    - key: workflow-FileGenerateNode
      val: 6.工作流/文档生成.md
    - key: workflow-FileParseNode
      val: 6.工作流/文档解析.md
    - key: workflow-TemplateTransformNode
      val: 6.工作流/模板转换.md
    - key: workflow-EndNode
      val: 6.工作流/结束.md
    - key: workflow-StartNode
      val: 6.工作流/开始.md

# --- middleware ---

minio:
  endpoint: localhost:9000
  user: root
  password: Wanwu123456

# --- microservice ---

iam:
  host: iam-service:8888

app:
  host: app-service:9988

model:
  host: model-service:8989
  ocr_test_file_path: "configs/microservice/bff-service/static/model/ocr.png"

mcp:
  host: mcp-service:9898

rag:
  host: rag-service:9640

assistant:
  host: assistant-service:8890

knowledge:
  host: knowledge-service:8889

workflow:
  host: http://agentscope-wanwu:6672
  workflow_list_uri: "/workflow/list"
  workflow_list_uri_internal: "/workflow/list_internal"
  delete_workflow_uri: "/workflow/delete"
  publish_workflow_uri: "/plugin/api/publish"
  unpublish_workflow_uri: "/plugin/api/unpublish"

agent:
  host: agent-wanwu
  upload_minio:
      port: 15001
      uri: /upload

operate:
  host: operate-service:9797