server:
  grpc_endpoint: 0.0.0.0:8888
  max_recv_msg_size: 4194304 # 1024 * 1024 * 4 = 4M

log:
  std: true
  level: debug
  logs:
    - enable: true
      filename: log/iam-info.log
      level: info
      max_size: 10
      max_backups: 10
      max_age: 30
    - enable: true
      filename: log/err-err.log
      level: error
      max_size: 10
      max_backups: 10
      max_age: 30

db:
  name: mysql # mysql | postgres | tidb | oceanbase
  mysql:
    address: localhost:3306
    user: root
    password: Wanwu123456
    database: iam_service
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  postgres:
    address: localhost:5432
    user: postgres
    password: Wanwu123456
    database: iam_service
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  tidb:
    address: localhost:4000
    user: root
    password: Wanwu123456
    database: iam_service
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true
  oceanbase:
    address: localhost:2881
    user: root@wanwu
    password: Wanwu123456
    database: iam_service
    max_open_conns: 16
    max_idle_conns: 16
    log_mode: true

redis:
  host: localhost
  port: 6379
  username:
  password: Wanwu123456
  standalone: true
  master_name: mymaster

smtp:
  host:
  port:
  username:
  password:
  default_from:
    email:
    name:

register:
  email:
    code_length: 4
    password_length: 8
    template:
      subject: "【元景万悟】欢迎使用联通元景万悟智能体平台"
      content_type: "text/html"
      body: |
        您好，<br /><br />
        您的邮箱验证码是：%s<br />
        您的初始登录密码是：%s<br /><br />
        验证码有效期为5分钟，请勿向他人透露。<br /><br />
        若非您本人发起，请忽略该邮件。<br /><br />
        如有任何问题欢迎加入QQ群：490071123<br /><br />
        感谢您的使用！<br />
        元景万悟团队

password:
  email:
    code_length: 4
    template:
      subject: "【元景万悟】欢迎使用联通元景万悟智能体平台"
      content_type: "text/html"
      body: |
        您好，<br /><br />
        您的邮箱验证码是：%s<br />
        验证码有效期为5分钟，请勿向他人透露。<br /><br />
        若非您本人发起，请忽略该邮件。<br /><br />
        如有任何问题欢迎加入QQ群：490071123<br /><br />
        感谢您的使用！<br />
        元景万悟团队